name: Push to release branches

on:
  push:
    branches:
      - apache-buster
      - apache-bookworm

env:
  PHP_VERSION: 8.2.27
  COMPOSER_VERSION: 2.8.5
  DEBIAN_VERSION: bookworm

jobs:
  Build-Push-Docker-Hub:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU to provide multiple architectures
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx to build for multiple architectures
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-architecture images
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            DEBIAN_VERSION=${{ env.DEBIAN_VERSION }}
            PHP_VERSION=${{ env.PHP_VERSION }}
            COMPOSER_VERSION=${{ env.COMPOSER_VERSION }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: voquis/cakephp:${{ env.PHP_VERSION }}-apache-${{ env.DEBIAN_VERSION }}
